services:
  market:
    container_name: market
    build:
      context: .
      dockerfile: Dockerfile
    image: market
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: market
      DB_USER: postgres
      DB_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: production

  db:
    container_name: postgres
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=market
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data: